// Generated by `pnpm openapi` from apps/api/openapi.json. Do not edit.
// Source of truth: the zod contracts and routes in apps/api and packages/schema.

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and readiness in one answer
         * @description 200 when the database answers and committed migrations are applied; 503 with the same body when either fails.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every dependency answers. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Database unreachable or migrations pending. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description ok when the database answers and migrations are current; degraded otherwise.
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** @description APP_VERSION injected at build time. */
            version: string;
            /** @description Short git commit the build was made from. */
            commit: string;
            /** @description ISO 8601 build timestamp. */
            builtAt: string;
            /**
             * Format: uri
             * @description Where the source of the running service is published (AGPL-3.0 section 13), to be read with `commit`. A modified deployment points this at its own source.
             */
            source: string;
            /**
             * @description SELECT 1 answered within 500 ms.
             * @enum {string}
             */
            db: "ok" | "unreachable";
            /**
             * @description Committed migrations compared with the ones applied to this database.
             * @enum {string}
             */
            migrations: "current" | "pending";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
