// Generated by `pnpm openapi` from apps/api/openapi.json. Do not edit.
// Source of truth: the zod contracts and routes in apps/api and packages/schema.

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and readiness in one answer
         * @description 200 when the database answers and committed migrations are applied; 503 with the same body when either fails.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every dependency answers. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Database unreachable or migrations pending. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin a bank login
         * @description Opened in the system browser by the app. Redirects to the identification broker's bank chooser; the person comes back through /auth/callback and the app receives a one-time code by deep link.
         */
        get: {
            parameters: {
                query: {
                    /** @description The app that will receive the one-time code by deep link. */
                    platform: "ios" | "android";
                    /** @description The language of the bank chooser (ui_locales); defaults to the request's. */
                    locale?: "fi" | "sv" | "en";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the broker. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No identification broker is configured. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The broker's return
         * @description The registered redirect URI. Exchanges the code with the broker, derives the identity, applies the re-registration rule and redirects to the app's deep link with a one-time code. Never called by the app itself.
         */
        get: {
            parameters: {
                query: {
                    code?: string;
                    state: string;
                    error?: string;
                    error_description?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to kuutti://auth?code=… on success, or to kuutti://auth?error=<code> (auth_state_mismatch, auth_cancelled, auth_under_18, auth_banned, auth_suspended, auth_cooldown with &until=<date>, auth_provider_error) so the app shows the refusal. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange the one-time code for a session
         * @description Single use, within 60 seconds of the callback. Answers with this device's access and refresh tokens; the app keeps both in secure storage.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthExchangeRequest"];
                };
            };
            responses: {
                /** @description The device's session. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthExchangeResponse"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unknown, used or expired code (auth_code_used). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the session's tokens
         * @description Presents the refresh token, receives a new pair; the old refresh token is retired. Presenting a retired token ends the device's session (session_revoked): sign in through the bank again.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthRefreshRequest"];
                };
            };
            responses: {
                /** @description The new pair. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionTokens"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Retired, revoked, expired or unknown refresh token (session_revoked). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This device's session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller's own session. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out this device */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The session is ended; both tokens stop working. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out every device
         * @description Recovery for a lost phone: every session of the account ends, including this one.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every session of the account is ended. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin a staff bank login
         * @description Opened by the moderation panel. The same bank login as the app's, marked as a staff attempt: it resolves to an identity with a moderator role and creates nothing. The browser returns to the panel with a one-time code in the URL fragment, or with error=admin_not_allowed.
         */
        get: {
            parameters: {
                query?: {
                    /** @description The language of the bank chooser; defaults to the request's. */
                    locale?: "fi" | "sv" | "en";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the broker. */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No identification broker is configured. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a staff one-time code for an admin session
         * @description Single use, within 60 seconds. Eight hours, no refresh; sign in again afterwards.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AdminAuthExchangeRequest"];
                };
            };
            responses: {
                /** @description The admin session. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminSession"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unknown, used or expired code (auth_code_used). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description admin_not_allowed: the role was taken away meanwhile. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This admin session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The role and when the session ends. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminWhoAmI"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this admin session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The session is ended. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete this account
         * @description Erasure per TD-7: every session, login attempt, photo (with its objects unless another account shares them), review row and fetch log entry goes; the account row stays as an anonymised tombstone and the identity keeps a deletion count and a 30-day cooldown before a new account. The audit log is untouched. The body confirms; the app asks first.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountDeletionRequest"];
                };
            };
            responses: {
                /** @description Erased. Every token of this account has stopped working. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed (confirm missing). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No live account: a second deletion that passed the session guard before the first committed (not_found). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything Kuutti holds about this account
         * @description One JSON document: the account, the identity's dates and login level, the devices signed in, the photos with fifteen-minute URLs and their moderation outcome, and the person's own fetch log. Nothing about anyone else.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The export. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountExport"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's photos
         * @description In the owner's order, with the blurhash to paint before the bytes arrive.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The caller's own photos. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoList"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Upload a photo
         * @description Multipart with one part named photo (JPEG, PNG or WebP, at most 10 MB). The API validates, strips metadata, re-encodes into three WebP variants and keeps no original. The photo is pending until moderation; the owner sees it, nobody else.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["PhotoUploadRequest"];
                };
            };
            responses: {
                /** @description Stored, pending moderation. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"];
                    };
                };
                /** @description Validation failed (no photo part, or not an accepted type). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_limit: the account has max_photos photos already. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description payload_too_large: over 10 MB. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_unsupported: the bytes are not a JPEG, PNG or WebP. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_too_many_pixels or photo_invalid: refused before or by the decoder. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description media_busy with Retry-After: image processing is at capacity; or media_unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a photo */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["PhotoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gone, along with its objects when nothing else shared them. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not a photo of this account. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the order of the photos
         * @description Position 0 is the main photo. Every photo of the account exactly once.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoOrderRequest"];
                };
            };
            responses: {
                /** @description The photos in the new order. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoList"];
                    };
                };
                /** @description Validation failed, or photo_order_invalid. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/{variant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A signed URL for one variant
         * @description Valid for fifteen minutes. Every issuance is logged against the caller and counts towards the exposure budget. The app caches by photo id and variant, never by this URL, and asks for full only from the zoom screen.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["PhotoId"];
                    /** @description thumb: 200×200 for lists. card: 800×1067 when a profile is opened. full: 1600 px long edge, requested only from the zoom screen. */
                    variant: components["schemas"]["PhotoVariant"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The URL and when it stops working. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoUrlResponse"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not a photo of this account. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description media_unavailable: no object storage is configured here. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/photos/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Photos waiting for a person's decision
         * @description Oldest first, with what the automatic check saw: labels with confidences, faces, what was flagged.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The queue. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoReviewQueue"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description admin_forbidden: the role does not allow this. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/photos/{id}/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A signed URL for the card variant, for review
         * @description Any photo, any state. Every issuance is an audit_log row naming the member of staff.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["PhotoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The URL and when it stops working. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoUrlResponse"];
                    };
                };
                /** @description Validation failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description admin_forbidden: the role does not allow this. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No such photo. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description media_unavailable: no object storage is configured here. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/photos/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve or reject a photo
         * @description approve makes the photo visible to others; reject hides it and tells the owner the reason in words. Only a queued photo takes a decision, once. Only a person rejects. Written to audit_log.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["PhotoId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoDecisionRequest"];
                };
            };
            responses: {
                /** @description The photo's new state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PhotoDecisionResponse"];
                    };
                };
                /** @description Validation failed (a rejection without a reason, for example). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description unauthenticated, session_expired or session_revoked. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description admin_forbidden: the role does not allow this. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No such photo. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description photo_not_queued: the photo is not waiting for a decision (already decided, or still being checked). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description ok when the database answers and migrations are current; degraded otherwise.
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** @description APP_VERSION injected at build time. */
            version: string;
            /** @description Short git commit the build was made from. */
            commit: string;
            /** @description ISO 8601 build timestamp. */
            builtAt: string;
            /**
             * Format: uri
             * @description Where the source of the running service is published (AGPL-3.0 section 13), to be read with `commit`. A modified deployment points this at its own source.
             */
            source: string;
            /**
             * @description SELECT 1 answered within 500 ms.
             * @enum {string}
             */
            db: "ok" | "unreachable";
            /**
             * @description Committed migrations compared with the ones applied to this database.
             * @enum {string}
             */
            migrations: "current" | "pending";
        };
        ErrorResponse: {
            error: {
                /** @description Stable machine-readable code. */
                code: string;
                /** @description Short, generic, safe to show. */
                message: string;
                /** @description Matches the API log line. */
                requestId: string;
            };
        };
        AuthExchangeResponse: {
            /**
             * Format: uuid
             * @description This device's session; the app keeps it with the tokens.
             */
            sessionId: string;
            /** @description Bearer token; valid until accessExpiresAt. */
            accessToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            /** @description Single use: /auth/refresh answers with a new pair and retires this one. */
            refreshToken: string;
            /**
             * Format: date-time
             * @description After this the device logs in through the bank again.
             */
            refreshExpiresAt: string;
            /**
             * @description created: a fresh account (first login or after a cooldown); resumed: the live account.
             * @enum {string}
             */
            outcome: "created" | "resumed";
        };
        AuthExchangeRequest: {
            /** @description The one-time code the deep link carried. */
            code: string;
        };
        SessionTokens: {
            /**
             * Format: uuid
             * @description This device's session; the app keeps it with the tokens.
             */
            sessionId: string;
            /** @description Bearer token; valid until accessExpiresAt. */
            accessToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            /** @description Single use: /auth/refresh answers with a new pair and retires this one. */
            refreshToken: string;
            /**
             * Format: date-time
             * @description After this the device logs in through the bank again.
             */
            refreshExpiresAt: string;
        };
        AuthRefreshRequest: {
            refreshToken: string;
        };
        SessionResponse: {
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            accountId: string;
            platform: components["schemas"]["AuthPlatform"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            refreshExpiresAt: string;
        };
        /** @enum {string} */
        AuthPlatform: "ios" | "android";
        AdminSession: {
            accessToken: string;
            /** Format: date-time */
            expiresAt: string;
            role: components["schemas"]["ModeratorRole"];
        };
        /** @enum {string} */
        ModeratorRole: "moderator" | "admin" | "researcher";
        AdminAuthExchangeRequest: {
            code: string;
        };
        AdminWhoAmI: {
            role: components["schemas"]["ModeratorRole"];
            /** Format: date-time */
            expiresAt: string;
        };
        AccountDeletionRequest: {
            /**
             * @description Must be true: the person confirmed in the app.
             * @enum {boolean}
             */
            confirm: true;
        };
        AccountExport: {
            /** Format: date-time */
            exportedAt: string;
            account: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                state: "registered" | "active" | "paused" | "shadow_banned" | "suspended" | "banned" | "deleted";
                /** Format: date-time */
                registeredAt: string;
                birthYear: number | null;
                birthMonth: number | null;
            };
            identity: {
                /** Format: date-time */
                firstSeenAt: string;
                /** Format: date-time */
                lastBankLoginAt: string | null;
                loginLevel: string | null;
                deletionCount: number;
            };
            sessions: {
                /** Format: uuid */
                sessionId: string;
                platform: components["schemas"]["AuthPlatform"];
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                lastUsedAt: string;
                /** Format: date-time */
                expiresAt: string;
            }[];
            photos: components["schemas"]["ExportedPhoto"][];
            photoAccessLog: {
                /** Format: uuid */
                photoId: string;
                variant: components["schemas"]["PhotoVariant"];
                /** Format: date-time */
                at: string;
            }[];
        };
        ExportedPhoto: {
            id: components["schemas"]["PhotoId"];
            /** @description Placeholder the app paints before the thumb arrives (computed from the thumb). */
            blurhash: string;
            /** @description Of the full variant. */
            width: number;
            /** @description Of the full variant. */
            height: number;
            state: components["schemas"]["PhotoState"];
            /**
             * @description Set when state is rejected: the reason the owner is told.
             * @enum {string|null}
             */
            rejectionReason: "nudity" | "no_person" | "several_people" | "minor" | "violence" | "contact_details" | "other" | null;
            /** @description 0 is the main photo; the owner sets the order. */
            position: number;
            /** Format: date-time */
            createdAt: string;
            urls: components["schemas"]["SignedVariantUrls"];
            /** @description The moderation outcome; label names are not part of it. */
            review: {
                /** @enum {string} */
                decision: "approved" | "queued" | "rejected";
                reason: components["schemas"]["PhotoRejectionReason"];
                /** @description True when a person decided, false when the automatic check did. */
                decidedByStaff: boolean;
                /** Format: date-time */
                decidedAt: string | null;
            } | null;
        };
        /** Format: uuid */
        PhotoId: string;
        /** @enum {string} */
        PhotoState: "pending" | "approved" | "queued" | "rejected";
        /** @description Fifteen-minute URLs, one per variant. */
        SignedVariantUrls: {
            /** Format: uri */
            thumb: string;
            /** Format: uri */
            card: string;
            /** Format: uri */
            full: string;
        } | null;
        /** @enum {string|null} */
        PhotoRejectionReason: "nudity" | "no_person" | "several_people" | "minor" | "violence" | "contact_details" | "other" | null;
        /**
         * @description thumb: 200×200 for lists. card: 800×1067 when a profile is opened. full: 1600 px long edge, requested only from the zoom screen.
         * @enum {string}
         */
        PhotoVariant: "thumb" | "card" | "full";
        PhotoList: {
            photos: components["schemas"]["Photo"][];
            /** @description matching_config max_photos. */
            maxPhotos: number;
        };
        Photo: {
            id: components["schemas"]["PhotoId"];
            /** @description Placeholder the app paints before the thumb arrives (computed from the thumb). */
            blurhash: string;
            /** @description Of the full variant. */
            width: number;
            /** @description Of the full variant. */
            height: number;
            state: components["schemas"]["PhotoState"];
            /**
             * @description Set when state is rejected: the reason the owner is told.
             * @enum {string|null}
             */
            rejectionReason: "nudity" | "no_person" | "several_people" | "minor" | "violence" | "contact_details" | "other" | null;
            /** @description 0 is the main photo; the owner sets the order. */
            position: number;
            /** Format: date-time */
            createdAt: string;
        };
        PhotoUploadRequest: {
            /**
             * Format: binary
             * @description The picture, pre-resized to 1600 px by the app; JPEG, PNG or WebP.
             */
            photo: string;
        };
        PhotoOrderRequest: {
            order: components["schemas"]["PhotoId"][];
        };
        PhotoUrlResponse: {
            /** Format: uri */
            url: string;
            variant: components["schemas"]["PhotoVariant"];
            /** Format: date-time */
            expiresAt: string;
        };
        PhotoReviewQueue: {
            items: components["schemas"]["PhotoReviewItem"][];
            total: number;
        };
        PhotoReviewItem: {
            photoId: components["schemas"]["PhotoId"];
            /** Format: uuid */
            accountId: string;
            state: components["schemas"]["PhotoState"];
            blurhash: string;
            width: number;
            height: number;
            /** Format: date-time */
            uploadedAt: string;
            /** Format: date-time */
            checkedAt: string | null;
            labels: components["schemas"]["ModerationLabel"][];
            faces: number;
            flagged: string[];
        };
        ModerationLabel: {
            name: string;
            parentName: string;
            confidence: number;
        };
        PhotoDecisionResponse: {
            photoId: components["schemas"]["PhotoId"];
            state: components["schemas"]["PhotoState"];
            rejectionReason: components["schemas"]["PhotoRejectionReason"];
        };
        PhotoDecisionRequest: {
            /** @enum {string} */
            decision: "approve";
        } | {
            /** @enum {string} */
            decision: "reject";
            reason: components["schemas"]["PhotoRejectionReason"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
