import { createHash } from "node:crypto";
import { type ArgumentType, argumentsOf, pseudoLocalise } from "./icu.ts";
import { isAdminKey, type Messages } from "./schema.ts";

const HEADER =
  "// Generated by `pnpm i18n:build` from messages.yaml. Do not edit: CI fails on drift.\n";

const TS_TYPE: Record<ArgumentType, string> = {
  string: "string",
  number: "number",
  date: "Date | number",
};

function catalogModule(name: string, catalog: Record<string, string>): string {
  const entries = Object.entries(catalog)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, text]) => `  ${JSON.stringify(key)}: ${JSON.stringify(text)},`)
    .join("\n");
  return `${HEADER}export const ${name}: Readonly<Record<string, string>> = {\n${entries}\n};\n`;
}

function keysModule(messages: Messages): string {
  const lines = Object.keys(messages)
    .sort((a, b) => a.localeCompare(b))
    .map((key) => {
      const args = Object.entries(argumentsOf(messages[key]?.en ?? ""));
      const shape =
        args.length === 0
          ? "Record<never, never>"
          : `{ ${args.map(([name, type]) => `${JSON.stringify(name)}: ${TS_TYPE[type]}`).join("; ")} }`;
      return `  ${JSON.stringify(key)}: ${shape};`;
    })
    .join("\n");
  return (
    `${HEADER}/** Every message key with the ICU arguments its English source takes. */\n` +
    `export type MessageParams = {\n${lines}\n};\n\nexport type MessageKey = keyof MessageParams;\n`
  );
}

/**
 * legal.<kind>.* wordings each carry a consent_version; a consent row must
 * name it to count (#46, ADR-010). One kind, one version: two versions under
 * one kind would mean a person could accept a wording nobody can point at.
 */
function consentModule(messages: Messages): string {
  const versions = new Map<string, Set<string>>();
  const locales = new Map<string, Set<string>>();
  const finnish = new Map<string, string[]>();
  for (const [key, message] of Object.entries(messages)) {
    const kind = key.split(".")[1];
    if (!key.startsWith("legal.") || !message.consent_version || !kind) continue;
    versions.set(kind, (versions.get(kind) ?? new Set()).add(message.consent_version));
    const present = locales.get(kind) ?? new Set<string>();
    for (const locale of ["fi", "sv", "en"] as const) if (message[locale]) present.add(locale);
    locales.set(kind, present);
    // The binding Finnish wording, key by key, so the hash names the text and not its order in the file.
    finnish.set(kind, [...(finnish.get(kind) ?? []), `${key}=${message.fi ?? ""}`].sort());
  }
  const kinds = [...versions.keys()].sort((a, b) => a.localeCompare(b));
  const versionLines = kinds
    .map((kind) => {
      const set = versions.get(kind) ?? new Set<string>();
      if (set.size > 1) {
        throw new Error(
          `legal.${kind}.* carries ${set.size} consent versions (${[...set].join(", ")}): one wording, one version`,
        );
      }
      return `  ${JSON.stringify(kind)}: ${JSON.stringify([...set][0])},`;
    })
    .join("\n");
  const localeLines = kinds
    .map(
      (kind) =>
        `  ${JSON.stringify(kind)}: ${JSON.stringify([...(locales.get(kind) ?? [])].sort())},`,
    )
    .join("\n");
  const hashLines = kinds
    .map(
      (kind) =>
        `  ${JSON.stringify(kind)}: ${JSON.stringify(
          createHash("sha256")
            .update((finnish.get(kind) ?? []).join("\n"))
            .digest("hex")
            .slice(0, 16),
        )},`,
    )
    .join("\n");
  return (
    `${HEADER}/** The consent_version each legal.<kind>.* wording belongs to: what a consent row must name to count (#46). */\n` +
    `export const CONSENT_VERSIONS: Readonly<Record<string, string>> = {\n${versionLines}\n};\n\n` +
    `/** The languages each wording exists in; a consent names one of these as the language it was shown in. */\n` +
    `export const CONSENT_TEXT_LOCALES: Readonly<Record<string, readonly string[]>> = {\n${localeLines}\n};\n\n` +
    `/** A fingerprint of the binding Finnish wording per kind: a golden test ties it to the version. */\n` +
    `export const CONSENT_TEXT_HASHES: Readonly<Record<string, string>> = {\n${hashLines}\n};\n`
  );
}

/**
 * messages.yaml compiled to the modules the runtimes import: one catalogue per
 * locale (a translation that is missing falls back to en at run time), the
 * en-XA pseudo-locale, and the key type that makes t() fail on a typo.
 * TypeScript modules rather than JSON: Metro, Vite, tsx, jest and vitest all
 * load them without a loader or an import attribute.
 */
export function compile(messages: Messages): Record<string, string> {
  const pick = (locale: "en" | "fi" | "sv"): Record<string, string> =>
    Object.fromEntries(
      Object.entries(messages).flatMap(([key, message]) => {
        const text = message[locale];
        return text === undefined ? [] : [[key, text] as const];
      }),
    );
  const en = pick("en");
  const pseudo = Object.fromEntries(
    Object.entries(en).map(([key, text]) => [key, isAdminKey(key) ? text : pseudoLocalise(text)]),
  );
  return {
    "en.ts": catalogModule("en", en),
    "fi.ts": catalogModule("fi", pick("fi")),
    "sv.ts": catalogModule("sv", pick("sv")),
    "en-XA.ts": catalogModule("enXA", pseudo),
    "keys.ts": keysModule(messages),
    "consent.ts": consentModule(messages),
  };
}
