import { type ArgumentType, argumentsOf, pseudoLocalise } from "./icu.ts";
import { isAdminKey, type Messages } from "./schema.ts";

const HEADER =
  "// Generated by `pnpm i18n:build` from messages.yaml. Do not edit: CI fails on drift.\n";

const TS_TYPE: Record<ArgumentType, string> = {
  string: "string",
  number: "number",
  date: "Date | number",
};

function catalogModule(name: string, catalog: Record<string, string>): string {
  const entries = Object.entries(catalog)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, text]) => `  ${JSON.stringify(key)}: ${JSON.stringify(text)},`)
    .join("\n");
  return `${HEADER}export const ${name}: Readonly<Record<string, string>> = {\n${entries}\n};\n`;
}

function keysModule(messages: Messages): string {
  const lines = Object.keys(messages)
    .sort((a, b) => a.localeCompare(b))
    .map((key) => {
      const args = Object.entries(argumentsOf(messages[key]?.en ?? ""));
      const shape =
        args.length === 0
          ? "Record<never, never>"
          : `{ ${args.map(([name, type]) => `${JSON.stringify(name)}: ${TS_TYPE[type]}`).join("; ")} }`;
      return `  ${JSON.stringify(key)}: ${shape};`;
    })
    .join("\n");
  return (
    `${HEADER}/** Every message key with the ICU arguments its English source takes. */\n` +
    `export type MessageParams = {\n${lines}\n};\n\nexport type MessageKey = keyof MessageParams;\n`
  );
}

/**
 * messages.yaml compiled to the modules the runtimes import: one catalogue per
 * locale (a translation that is missing falls back to en at run time), the
 * en-XA pseudo-locale, and the key type that makes t() fail on a typo.
 * TypeScript modules rather than JSON: Metro, Vite, tsx, jest and vitest all
 * load them without a loader or an import attribute.
 */
export function compile(messages: Messages): Record<string, string> {
  const pick = (locale: "en" | "fi" | "sv"): Record<string, string> =>
    Object.fromEntries(
      Object.entries(messages).flatMap(([key, message]) => {
        const text = message[locale];
        return text === undefined ? [] : [[key, text] as const];
      }),
    );
  const en = pick("en");
  const pseudo = Object.fromEntries(
    Object.entries(en).map(([key, text]) => [key, isAdminKey(key) ? text : pseudoLocalise(text)]),
  );
  return {
    "en.ts": catalogModule("en", en),
    "fi.ts": catalogModule("fi", pick("fi")),
    "sv.ts": catalogModule("sv", pick("sv")),
    "en-XA.ts": catalogModule("enXA", pseudo),
    "keys.ts": keysModule(messages),
  };
}
