/**
 * Writes apps/api/openapi.json from the running contracts and regenerates
 * packages/schema/src/api.generated.ts with openapi-typescript (ADR-003).
 * CI runs this and fails on a diff, so the committed files never drift.
 *
 *   pnpm openapi
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";
import { pino } from "pino";
import { createApp } from "../src/app.ts";
import { parseConfig } from "../src/lib/config.ts";
import { openApiDocument } from "../src/lib/openapi.ts";

const here = resolve(import.meta.dirname, "..");
const version = (
  JSON.parse(readFileSync(resolve(here, "package.json"), "utf8")) as { version: string }
).version;

const app = createApp({
  config: parseConfig({
    NODE_ENV: "test",
    APP_ENV: "test",
    DATABASE_URL: "postgres://unused",
    APP_VERSION: version,
  }),
  logger: pino({ level: "silent" }),
  db: {
    query: () => {
      throw new Error("the document generator never queries");
    },
  },
});

const document = app.getOpenAPIDocument(openApiDocument(version));
const jsonPath = resolve(here, "openapi.json");
writeFileSync(jsonPath, `${JSON.stringify(document, null, 2)}\n`);

const ast = await openapiTS(new URL(`file://${jsonPath}`), { exportType: false });
const header = `// Generated by \`pnpm openapi\` from apps/api/openapi.json. Do not edit.\n// Source of truth: the zod contracts and routes in apps/api and packages/schema.\n\n`;
const typesPath = resolve(here, "..", "..", "packages", "schema", "src", "api.generated.ts");
writeFileSync(typesPath, header + astToString(ast));

console.log(`wrote ${jsonPath}\nwrote ${typesPath}`);
